### ISSUE TITLE
Hexo博客Next主题集成第三方服务 | 亿界博客

### ISSUE THREAD

**Issue by nelou100** [nelou100/gitment#80]
http://www.0101tx.com/pages/hexonextsanf.html

**Comment by nelou100** [comment]
``` java
public class HelloWorld {
    public static void main(String[] args) {
        System.out.println("Hello World");
    }
}
```

**Comment by nelou100** [comment]
``` html

<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>亿界博客(0101tx.com)</title>
</head>
<body>
    <h1>我的第一个标题</h1>
    <p>我的第一个段落。</p>
</body>
</html>

```

**Comment by nelou100** [comment]
``` css

body
{
    background-color:#d0e4fe;
}
h1
{
    color:orange;
    text-align:center;
}
p
{
    font-family:"Times New Roman";
    font-size:20px;
}

```
